### ISSUE TITLE
USB 2 compatibility?

### ISSUE THREAD

**Issue by KR155E** [cr1901/prog-vb#1]
Testing on Windows 10 with a FlashBoy Plus, I kept getting error messages when using a USB 2 port:

"Error: hidapi error: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen."

(Through Google Translate: "Error: hidapi error: I / O operation was aborted due to thread end or application request.")

After I switched from USB 2 to USB 3, it worked just fine.

**Comment by cr1901** [comment]
FlashBoy only uses USB Full Speed; it should be happy even in a USB 1.1-only port. And of course it "works on my machine :P".

Clearly that isn't helpful to you. FlashBoy should be working in your USB 2.0 port; I need to return superior error messages to know where `hidapi` is dying.

@KR155E Do you have `rustc` installed, and are you capable of building your own copy of `prog-vb`? I can [enable backtraces](https://docs.rs/failure/0.1.5/failure/#backtraces) to get more info...

**Comment by KR155E** [comment]
Nevermind, @cr1901! It appears my machine's front panel USB2 port is faulty. I tried it with a few different ones on the back as well as another one that's part of a multi card reader, and they worked fine. :-)

**Comment by cr1901** [comment]
@KR155E Excellent, glad you were able to solve the issue :).

Just for future reference, would you be willing to build your own copy of `prog-vb` for testing if problems should arise?

This program isn't that big; I should add the backtrace feature anyway just in case...

**Comment by KR155E** [comment]
Sorry, I don't think I can find the time to look into setting up a Rust building pipeline. :-/
